# Generated by Django 4.0.1 on 2022-02-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'Directeur'), ('2', 'Vendeur'), ('3', 'Autre')], default='2', max_length=10),
        ),
    ]
