# Generated by Django 4.0.1 on 2022-02-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_user_type'),
    ]

    operations = [
    ]
