# Generated by Django 4.0.1 on 2022-04-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ficheventeclient',
            name='type_client',
            field=models.CharField(choices=[('Détaillant', 'Détaillant'), ('Grossiste', 'Grossiste'), ('Revendeur', 'Revendeur'), ('Autre', 'Autre')], default=1, max_length=30),
        ),
    ]
