# Generated by Django 4.0.1 on 2022-02-27 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendeur',
            name='identity_num',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='Transporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('vehicule', models.CharField(max_length=100)),
                ('poids', models.PositiveIntegerField()),
                ('id_num', models.PositiveBigIntegerField(unique=True)),
                ('selling_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sellingpoint')),
            ],
        ),
        migrations.CreateModel(
            name='Clarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('vehicule', models.CharField(max_length=100)),
                ('poids', models.PositiveIntegerField()),
                ('id_num', models.PositiveBigIntegerField(unique=True)),
                ('selling_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sellingpoint')),
            ],
        ),
    ]
