# Generated by Django 4.0.1 on 2022-01-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='saisie_par',
        ),
        migrations.RemoveField(
            model_name='ficheachatcommandefournisseur',
            name='saisie_par',
        ),
        migrations.RemoveField(
            model_name='ficheventeclient',
            name='saisie_par',
        ),
        migrations.RemoveField(
            model_name='fraisgenerales',
            name='saisie_par',
        ),
        migrations.RemoveField(
            model_name='payementclient',
            name='saisie_par',
        ),
        migrations.RemoveField(
            model_name='payementfournisseur',
            name='saisie_par',
        ),
        migrations.RemoveField(
            model_name='retoursclient',
            name='saisie_par',
        ),
        migrations.RemoveField(
            model_name='retoursfournisseur',
            name='saisie_par',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='admin',
        ),
    ]
