# Generated by Django 4.0.1 on 2022-03-17 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheachatcommandefournisseur',
            name='numero',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ficheachatcommandefournisseur',
            name='modifie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifie_par_fac', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ficheachatcommandefournisseur',
            name='saisie_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saisie_par_fac', to=settings.AUTH_USER_MODEL),
        ),
    ]
