# Generated by Django 4.0.1 on 2022-01-30 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_caisse_solde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendeur',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/produits/'),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='adress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='family_situation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='identity_num',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='phone_number_1',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='phone_number_2',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='selling_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sellingpoint'),
        ),
    ]
