# Generated by Django 4.0.1 on 2022-03-20 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ficheachatcommandefournisseur_numero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='fraisgenerales',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.typefg'),
        ),
    ]
