# Generated by Django 4.0.1 on 2022-02-02 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='selling_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.sellingpoint'),
        ),
    ]
