# Generated by Django 4.0.1 on 2022-01-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vendeur_img_alter_vendeur_adress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='adress',
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='adresse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='telephone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='ville',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='wilaya',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
