# Generated by Django 4.0.1 on 2022-02-09 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_ficheachatcommandefournisseur_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitachatcommandefournisseur',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_achat_fournisseur', to='core.produit'),
        ),
    ]
