# Generated by Django 4.0.1 on 2022-03-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_typefg_alter_fraisgenerales_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraisgenerales',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
