# Generated by Django 4.0.1 on 2022-03-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fraisgenerales_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaries',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
