# Generated by Django 4.0.1 on 2022-01-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_fournisseur_adress_fournisseur_adresse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fournisseur',
            old_name='selling_ponit',
            new_name='selling_point',
        ),
    ]
