# Generated by Django 4.0.1 on 2022-02-09 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_produitachatcommandefournisseur_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitachatcommandefournisseur',
            name='achat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='core.ficheachatcommandefournisseur'),
        ),
    ]
