# Generated by Django 4.0.1 on 2022-01-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_selling_ponit_fournisseur_selling_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheachatcommandefournisseur',
            name='article',
            field=models.CharField(max_length=10),
        ),
    ]
