# Generated by Django 4.0.1 on 2022-02-09 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_produitachatcommandefournisseur_achat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficheventeclient',
            name='code',
        ),
        migrations.RemoveField(
            model_name='ficheventeclient',
            name='depot',
        ),
        migrations.RemoveField(
            model_name='ficheventeclient',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='ficheventeclient',
            name='prixHT',
        ),
        migrations.RemoveField(
            model_name='ficheventeclient',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='ficheventeclient',
            name='quantite',
        ),
        migrations.AddField(
            model_name='ficheventeclient',
            name='modifie_par',
            field=models.ForeignKey(default=1111, on_delete=django.db.models.deletion.CASCADE, related_name='modifie_par_vc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ficheventeclient',
            name='saisie_par',
            field=models.ForeignKey(default=1111, on_delete=django.db.models.deletion.CASCADE, related_name='saisie_par_vc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProduitVenteClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_lot', models.IntegerField()),
                ('date_de_fabrication', models.DateField()),
                ('date_dexpiration', models.DateField()),
                ('unit', models.CharField(choices=[('1', 'm²'), ('2', 'm'), ('3', 'L'), ('4', 'Kg'), ('4', 'g')], max_length=10)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.depot')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_vente_client', to='core.produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='core.ficheventeclient')),
            ],
        ),
    ]
