# Generated by Django 4.0.1 on 2022-02-11 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_remove_ficheventeclient_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retoursfournisseur',
            name='depot',
        ),
        migrations.RemoveField(
            model_name='retoursfournisseur',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='retoursfournisseur',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='retoursfournisseur',
            name='qtte_achetée',
        ),
        migrations.RemoveField(
            model_name='retoursfournisseur',
            name='qtte_retour',
        ),
        migrations.AddField(
            model_name='produitachatcommandefournisseur',
            name='quantite_retour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='retoursfournisseur',
            name='modifie_par',
            field=models.ForeignKey(default=1111, on_delete=django.db.models.deletion.CASCADE, related_name='modifie_par_rf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retoursfournisseur',
            name='selling_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.sellingpoint'),
        ),
        migrations.AlterField(
            model_name='retoursfournisseur',
            name='saisie_par',
            field=models.ForeignKey(default=1111, on_delete=django.db.models.deletion.CASCADE, related_name='saisie_par_rf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProduitsRetourFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_retour', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='produit_retour_fournisseur', to='core.produit')),
                ('retour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='core.retoursfournisseur')),
            ],
        ),
    ]
