# Generated by Django 4.0.1 on 2022-04-08 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_ficheventeclient_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheventeclient',
            name='modifie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifie_par_vc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ficheventeclient',
            name='type_client',
            field=models.CharField(choices=[('détaillant', 'détaillant'), ('grossiste', 'grossiste'), ('revendeur', 'revendeur'), ('autre', 'autre')], default=1, max_length=30),
        ),
    ]
