# Generated by Django 4.0.1 on 2022-02-11 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_produit_qtte_achete_produit_qtte_avarie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retoursfournisseur',
            name='modifie_par',
            field=models.ForeignKey(default=1111, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifie_par_rf', to=settings.AUTH_USER_MODEL),
        ),
    ]
