# Generated by Django 4.0.1 on 2022-02-11 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_alter_retoursfournisseur_modifie_par'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitsretourfournisseur',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_retour_fournisseur', to='core.produit'),
        ),
        migrations.AlterField(
            model_name='retoursfournisseur',
            name='modifie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifie_par_rf', to=settings.AUTH_USER_MODEL),
        ),
    ]
