# Generated by Django 4.0.1 on 2022-02-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_produitsretourfournisseur_produit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='stock_actuel',
        ),
    ]
