# Generated by Django 4.0.1 on 2022-02-12 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_remove_produit_stock_actuel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficheventeclient',
            name='reste_a_payer',
        ),
        migrations.RemoveField(
            model_name='produitventeclient',
            name='date_de_fabrication',
        ),
        migrations.RemoveField(
            model_name='produitventeclient',
            name='date_dexpiration',
        ),
        migrations.RemoveField(
            model_name='produitventeclient',
            name='unit',
        ),
        migrations.AlterField(
            model_name='ficheventeclient',
            name='modifie_par',
            field=models.ForeignKey(default=1111, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifie_par_vc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Avaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtte', models.PositiveBigIntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produit')),
                ('selling_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sellingpoint')),
            ],
        ),
    ]
