# Generated by Django 4.0.1 on 2022-02-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_ficheventeclient_reste_a_payer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficheventeclient',
            name='solde',
        ),
        migrations.AlterField(
            model_name='ficheventeclient',
            name='montant_reg_client',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
