# Generated by Django 4.0.1 on 2022-02-13 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_remove_payementclient_solde_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retoursclient',
            name='achat',
        ),
        migrations.RemoveField(
            model_name='retoursclient',
            name='depot',
        ),
        migrations.RemoveField(
            model_name='retoursclient',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='retoursclient',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='retoursclient',
            name='qtte_achetée',
        ),
        migrations.RemoveField(
            model_name='retoursclient',
            name='qtte_retour',
        ),
        migrations.AddField(
            model_name='retoursclient',
            name='modifie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifie_par_rc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retoursclient',
            name='selling_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.sellingpoint'),
        ),
        migrations.AddField(
            model_name='retoursclient',
            name='vente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.ficheventeclient'),
        ),
        migrations.AlterField(
            model_name='retoursclient',
            name='saisie_par',
            field=models.ForeignKey(default=1111, on_delete=django.db.models.deletion.CASCADE, related_name='saisie_par_rc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProduitsRetourClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_retour', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_retour_client', to='core.produit')),
                ('retour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='core.retoursclient')),
            ],
        ),
    ]
