# Generated by Django 4.0.1 on 2022-02-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_retoursclient_achat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payementfournisseur',
            name='solde',
        ),
        migrations.AddField(
            model_name='caisse',
            name='montant_achats_four',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='caisse',
            name='montant_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='caisse',
            name='montant_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='caisse',
            name='montant_frais_generales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='caisse',
            name='montant_pay_client',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='caisse',
            name='montant_pay_four',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='caisse',
            name='montant_retour_client',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='caisse',
            name='montant_retour_four',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='caisse',
            name='montant_vente_client',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ficheventeclient',
            name='type_client',
            field=models.CharField(choices=[('1', 'Bon de livraison'), ('2', 'Facture'), ('2', 'BL sans montant'), ('2', 'Facture proformat')], default=1, max_length=10),
        ),
    ]
