# Generated by Django 4.0.1 on 2022-02-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_payementfournisseur_solde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheventeclient',
            name='reste_a_payer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
